// Placer les objets directement par le script et non par les sorts
// Répète l'opération pour Player1, ... Player6
IF
	// S'assure qu'on fait ça après avoir été dépouillé et après la scène d'Irenicus
	Global("TakeImportItems","AR0602",1)
	// S'assure que ça ne se fera que pour le chantelame
	// Inspiration : TDD, qui vérifie dans DPLAYER si le joueur est anti-paladin
	// MAHBLADESINGER est le nom utilisé partout dans ADD_KIT
	Kit(Player1,MAHBLADESINGER)
	// S'assure que ce bloc ne va s'exécuter à l'infini
	Global("ChantelameVerifPlayer1","AR0602",0)
THEN
	RESPONSE #100
		// Exemple tiré de BGT pour placer la ceinture à Imoen
		ActionOverride(Player1,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player1,FillSlot(SLOT_ARMOR))
		// En principe, le perso n'a plus rien sur lui donc il n'y a pas ambiguité
		// sur ce qu'il peut mettre comme armure ou bouclier : FillSlot prend un
		// élément satisfaisant, pas forcément celui qu'on veut (mais ici ça ira).
		// Assure qu'on ne répètera pas le bloc
		SetGlobal("ChantelameVerifPlayer1","AR0602",1)
END

IF
	Global("TakeImportItems","AR0602",1)
	Kit(Player2,MAHBLADESINGER)
	Global("ChantelameVerifPlayer2","AR0602",0)
THEN
	RESPONSE #100
		ActionOverride(Player2,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player2,FillSlot(SLOT_ARMOR))
		SetGlobal("ChantelameVerifPlayer2","AR0602",1)
END

IF
	Global("TakeImportItems","AR0602",1)
	Kit(Player3,MAHBLADESINGER)
	Global("ChantelameVerifPlayer3","AR0602",0)
THEN
	RESPONSE #100
		ActionOverride(Player3,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player3,FillSlot(SLOT_ARMOR))
		SetGlobal("ChantelameVerifPlayer3","AR0602",1)
END

IF
	Global("TakeImportItems","AR0602",1)
	Kit(Player4,MAHBLADESINGER)
	Global("ChantelameVerifPlayer4","AR0602",0)
THEN
	RESPONSE #100
		ActionOverride(Player4,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player4,FillSlot(SLOT_ARMOR))
		SetGlobal("ChantelameVerifPlayer4","AR0602",1)
END

IF
	Global("TakeImportItems","AR0602",1)
	Kit(Player5,MAHBLADESINGER)
	Global("ChantelameVerifPlayer5","AR0602",0)
THEN
	RESPONSE #100
		ActionOverride(Player5,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player5,FillSlot(SLOT_ARMOR))
		SetGlobal("ChantelameVerifPlayer5","AR0602",1)
END

IF
	Global("TakeImportItems","AR0602",1)
	Kit(Player6,MAHBLADESINGER)
	Global("ChantelameVerifPlayer6","AR0602",0)
THEN
	RESPONSE #100
		ActionOverride(Player6,CreateItem("pxlarmor",1,0,0))	// Armure
		ActionOverride(Player6,FillSlot(SLOT_ARMOR))
		SetGlobal("ChantelameVerifPlayer6","AR0602",1)
END
